apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ivolve
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: my-data
          persistentVolumeClaim:
            claimName: app-pvc
      tolerations:
      - key: "workload"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      containers:
        - name: web
          image: mohamed2200/django-web-blog:11
          command: ["sh", "-c"]
          args: 
          - |
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py shell -c "
            import os;
            from django.contrib.auth.models import User;
            user, created = User.objects.get_or_create(
                username=os.environ['DJANGO_SUPERUSER_USERNAME'],
                defaults={
                  'email': os.environ['DJANGO_SUPERUSER_EMAIL'],
                  'is_superuser': True,
                  'is_staff': True
                }
            );
            user.set_password(os.environ['DJANGO_SUPERUSER_PASSWORD']);
            user.save()
            " &&
            python manage.py runserver 0.0.0.0:8000
          ports:
            - name: http
              containerPort: 8000

          envFrom:
            - configMapRef:
                name: django-config
          env:
          - name: DATABASE_URL
            value: "postgresql://postgres:postgres@db:5432/postgres"
