apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-db-data-db-0
  namespace: ivolve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: my-db-pv
