apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: ivolve
spec:
  claimRef:
    name: app-pvc
    namespace: default 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /test
