apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-nginx-conf
  namespace: default
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://54.235.196.199:8080;
      }
    }
